### ISSUE TITLE
pi 2 breaks wiringpi2

### ISSUE THREAD

**Issue by jdawgaz** [WiringPi/WiringPi-Ruby#10]
Wiringpi2 does not work for Raspberry pi 2.

**Comment by jdawgaz** [comment]
Hmm. No comments?
is anyone even looking after this repo anymore?

**Comment by agarie** [comment]
The last commit was [in 2013](https://github.com/WiringPi/WiringPi2-Ruby/commits/master), so I guess not. :(

**Comment by Gadgetoid** [comment]
I haven't touched Ruby for a long time, since the overwhelming demand was for Python, but it's on my radar for an update.

**Comment by jdawgaz** [comment]
I don't know how this got closed (it said I did).
So unless this has been fixed. I am reopening.

**Comment by Gadgetoid** [comment]
This should be fixed as of `2.32.0` but I haven't picked up Ruby in a long, long time so feedback on the latest published module and its shortcomings is appreciated.
