### ISSUE TITLE
Does it work on RPi 3?

### ISSUE THREAD

**Issue by ermaker** [WiringPi/WiringPi-Ruby#15]
It seems to not work on My RPi 3. Does this library support RPi 2 only?

**Comment by Gadgetoid** [comment]
I think the copy of WiringPi embedded in this repository is now a little out of date- I'll need to update it!

**Comment by Gadgetoid** [comment]
Actually, I'm not so sure that's true. I've just installed, and the Binary Clock example works on my Pi 3. What problems are you having?

**Comment by ermaker** [comment]
Thank you for quick reply.

The result between gpio and wiringpi2 on ruby is different and I think gpio is correct.

```sh
pi@raspberrypi:~ $ gem list --local wiringpi2                                                                 
*** LOCAL GEMS ***

wiringpi2 (2.0.1)
pi@raspberrypi:~ $ sudo ruby -rwiringpi2 -e 'puts WiringPi::GPIO.new {|io| io.pin_mode(7, WiringPi::INPUT)}.digital_read(7)' ; gpio read 7
1
0
```

Please ask me more information you need.

**Comment by ermaker** [comment]
I checked once more and I think I catch up the reason.

I installed wiringpi2 because the main page of this project says 'install wiringpi2', but updated gem  to 2.23.0 is wiringpi.

Should I use `wiringpi` gem instead of `wiringpi2`?

**Comment by ermaker** [comment]
I made pull request to fix the reason I confused. Please check it out.

**Comment by Souravgoswami** [comment]
Hello, I am using Raspberry Pi 3 and Arch Linux ARM.
Wiringpi2 is not working for me.

I can get the wiringpi (shell) working.

Whenever I run the codes as instructed, it does nothing. No Errors, and nothing. The code exits gracefully without working.
