### ISSUE TITLE
GPIO.interrupt doesn't work?

### ISSUE THREAD

**Issue by hertling** [WiringPi/WiringPi-Ruby#17]
Does the GPIO interrupt method work, and if so, how is it used? An example would be great. I'm trying to monitor switches.

I currently do:

```
require 'wiringpi'
gpio = WiringPi::GPIO.new
gpio.pin_mode 7, WiringPi::INPUT
gpio.interrupt 7, :both do |pin_state|
  puts "pin changed to #{pin_state}"
end

while true
  sleep 1.0
end
```

But I never see my code executed. I can poll using gpio.digital_read(7) and see the pin state change, so I know the circuit is correct, and I have the right pin.

I'm on ruby 2.1.5p273, with wiringpi 2.32.0, on a Raspberry Pi 3.

**Comment by nitsujri** [comment]
I know this is 2 years old but reading the [interrupt definition for event](https://github.com/WiringPi/WiringPi-Ruby/blob/master/lib/wiringpi/event.rb) there's a break if the current `@value` doesn't match the expected rising/falling edge.

It breaks without notification/error which is likely what's happening here.

If anyone else is looking at this and wondering, I would recommend setting the `pull` before starting the interrupt.
