### ISSUE TITLE
Update readme for new instructions

### ISSUE THREAD

**Issue by markrickert** [WiringPi/WiringPi-Ruby#2]
I wasn't able to get WiringPi2 to work at all without some major modifications to the example in the documentation. It should probably be updated.

I'll put the way I got it working here in hopes that it helps someone else.

Gemfile
```ruby
gem 'wiringpi2', :github => 'Gadgetoid/WiringPi2-Ruby'
```

program.rb
```ruby
#!/usr/bin/env ruby

require 'bundler'
Bundler.setup
Bundler.require

io = WiringPi::GPIO.new do |gpio|
	# Set the pinmode of pin 0 for output
	gpio.pin_mode(0, 1)
end

# Turn pin 0 on
io.digital_write(0, 1)
# Wait
io.delay(100)
# Turn pin 0 off
io.digital_write(0, 0)
```

**Comment by elliotthilaire** [comment]
This is helpful. Thank you @markrickert
