### ISSUE TITLE
Release version 2 of 'wiringpi' gem with latest code

### ISSUE THREAD

**Issue by andrewn** [WiringPi/WiringPi-Ruby#4]
Hi!

I see that an earlier version of this Ruby wrapper as `wiringpi` on Rubygems. Could you push the latest code in master as version 2.0 of the gem please?

**Comment by Gadgetoid** [comment]
I consider "WiringPi" defunct enough now that I could safely replace it with this version. Will look into it as part of my Pi 2 compatibility push.

**Comment by Gadgetoid** [comment]
All code as of https://github.com/WiringPi/WiringPi-Ruby/commit/73e90d8cab45c40bb01d529cf61a9c1633fd1869 has been pushed to rubygems as WiringPi 2.0.0.
